version: '3.8'

services:
  development:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
      target: development  # 'development' stage
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  production:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
      target: production  # 'production'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
