version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
